name: Convert Markdown to PDF

on:
#  push:
#    tags:
#      - '*'
  release:
    types: [published]  # o created
    
jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pandoc e LaTeX (per il rendering PDF)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-latex-recommended

      - name: Generate PDF
        run: |
          NAME=$(echo "${{ github.event.release.tag_name }}" | cut -d'-' -f2-)
          echo "NAME=$NAME" >> "$GITHUB_ENV"
          cd $NAME
          echo "$NAME"
          # ls -l
          pandoc --defaults ./md2pdf.yml \
            -o ${{ github.repository }}-$NAME-${{ github.event.release.tag_name }}.pdf

      - name: Upload PDF as release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.repository }}-$NAME-${{ github.event.release.tag_name }}.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
